global:
  scrape_interval: 5s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: 
          - node-exporter:9100

  - job_name: frontend
    static_configs:
      - targets: 
          - frontend:5173
    # metrics_path: '/actuator/prometheus'

  - job_name: backand
    static_configs:
      - targets: 
          - backand:8585
    # metrics_path: '/actuator/prometheus'

  - job_name: postgres
    static_configs:
      - targets: 
          - exporter_container:9187
    # metrics_path: '/actuator/exporter_container'