apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backand
  name: backand
spec:
  ports:
    - name: "8585"
      port: 8585
      targetPort: 8585
  selector:
    io.kompose.service: backand
  # minReplicas: 1
  # maxReplicas: 2
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     targetAverageUtilization: 15
