apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: backand
  name: backand
spec:
  containers:
    - args:
        - python
        - ./server_rule.py
      image: edenchik/devopslab:backand.2.0.0
      name: backand
      ports:
        - containerPort: 8585
          protocol: TCP
  restartPolicy: OnFailure
