apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: node-exporter
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: node-exporter
    spec:
      containers:
        - args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($()|/)
          env:
            - name: TZ
              value: Europe/Moscow
          image: prom/node-exporter
          name: exporter
          ports:
            - containerPort: 9100
              protocol: TCP
          volumeMounts:
            - mountPath: /host/proc
              name: node-exporter-claim0
              readOnly: true
            - mountPath: /host/sys
              name: node-exporter-claim1
              readOnly: true
      hostname: exporter
      restartPolicy: Always
      volumes:
        - name: node-exporter-claim0
          persistentVolumeClaim:
            claimName: node-exporter-claim0
            readOnly: true
        - name: node-exporter-claim1
          persistentVolumeClaim:
            claimName: node-exporter-claim1
            readOnly: true
