apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postgres-exporter
  name: postgres_exporter
spec:
  ports:
    - name: "9187"
      port: 9187
      targetPort: 9187
  selector:
    io.kompose.service: postgres-exporter
