name: Docker Image CI

on:
  push:
    branches: [ "Lab-3" ]
  pull_request:
    branches: [ "Lab-3" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: the Docker build
      run: docker compose -f docker-compose.yml up -d --wait 
  
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
      name: the test 

    #   run: docker compose -f docker-compose.yml up -d --wait

    - name: Setup Python 3.12.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.1

    - name: Install python
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-selenium
        pip install psycopg2
        pip install flask
        pip install flask_cors
        pip install prometheus-flask-exporter

    - name: Tested backend
      run: |
        pytest ./backend/back_test.py::test_isCreated_DB_table_exists
        pytest ./backend/back_test.py::test_isCreated_DB_table_not_exists
        pytest ./backend/back_test.py::test_AllEntries
        pytest ./backend/back_test.py::test_Insert_DB
        pytest ./backend/back_test.py::test_Update_DB
        pytest ./backend/back_test.py::test_Delete_DB
        pytest ./backend/back_test.py::test_jsoncreat
        pytest ./backend/back_test.py::test_get_endpoint
        pytest ./backend/back_test.py::test_post_endpoint
        pytest ./backend/back_test.py::test_put_endpoint
        pytest ./backend/back_test.py::test_delete_endpoint

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.14'
        registry-url: 'https://registry.npmjs.org'  

    - name: NMP update
      run: |
        cd frontend
        npm update

    - name: Tested frontend
      run: |
        cd frontend
        npm run build --if-present       
        npm run test

  docker_push:
    name: docker_push
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4

    - name: Set Docker tag
      id: vars
      run: echo "TAG=2.0.0" >> $GITHUB_ENV

    - name: Build backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devopslab:backend.${{ env.TAG }} ./backend

    - name: Build frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devopslab:frontend.${{ env.TAG }} ./frontend    

    - name: Login Docker
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Export Backend
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/devopslab:backend.${{ env.TAG }}   

    - name: Export Frontend
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/devopslab:frontend.${{ env.TAG }}
    