name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml up -d --wait
    - uses: actions/checkout@v12
    - name: test backand
    - name: Display Python version
      run: pytest ./backand/back_test.ry::client      
    - name: test frontend
