name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml up -d --wait

      uses: actions/setup-python@v4
      with:
        python-version: 3.12.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-selenium  
   
    - name: Test with PyTest
      run: pytest --html=tests/Reports/Report.html  

    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Pytest Report           # Name of the folder
        path: tests/Reports           # Path to test results