name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml up -d --wait

    - name: Setup Python 3.12.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.1

    - name: Install python
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-selenium
        pip install psycopg2
        pip install flask
        pip install flask_cors
        pip install prometheus-flask-exporter

    - name: Tested backand
      run: |
        pytest ./backand/back_test.py::test_isCreated_DB_table_exists
        pytest ./backand/back_test.py::test_isCreated_DB_table_not_exists
        pytest ./backand/back_test.py::test_AllEntries
        pytest ./backand/back_test.py::test_Insert_DB
        pytest ./backand/back_test.py::test_Update_DB
        pytest ./backand/back_test.py::test_Delete_DB
        pytest ./backand/back_test.py::test_jsoncreat
        pytest ./backand/back_test.py::test_get_endpoint
        pytest ./backand/back_test.py::test_post_endpoint
        pytest ./backand/back_test.py::test_put_endpoint
        pytest ./backand/back_test.py::test_delete_endpoint

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16.14'
        registry-url: 'https://registry.npmjs.org'  

    - name: NMP setup
      run: |
        cd frontend
        npm update

    - name: Tested frontend
      run: |
        cd frontend
        npm run build --if-present        
        npm run test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.12.1
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.1

    - name: Update python
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-selenium
        pip install psycopg2
        pip install flask
        pip install flask_cors
        pip install prometheus-flask-exporter

    - name: Tested backand
      run: |
        pytest ./backand/back_test.py
    
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml up -d --wait

    

    